httpProxy: null

httpsProxy: null

nodeLinker: node-modules

#npmRegistryServer: "http://192.168.6.3:16031/repository/npm-h/"
#npmRegistryServer: "https://registry.yarnpkg.com"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

#unsafeHttpWhitelist: 192.168.6.3

yarnPath: .yarn/releases/yarn-3.4.1.cjs
